'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BITACORA_ENVIO_SWIFT
    Public Property no_envio_swift As Integer
    Public Property no_rep_swift As Integer
    Public Property archivo As String
    Public Property fecha_envio As Date
    Public Property fecha_validado As Nullable(Of Date)
    Public Property reenvio As Boolean
    Public Property ultimo_reporte As Boolean
    Public Property status_envio As Byte

End Class
