'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BLOQUEO_OBSERVACION
    Public Property bloqueo_observacion1 As Byte
    Public Property descripcion_bloqueo_observacio As String
    Public Property status_bloqueo As Byte
    Public Property posicion_bloqueo As Nullable(Of Byte)

    Public Overridable Property BLOQUEO_CUENTAS_DINAMICO As ICollection(Of BLOQUEO_CUENTAS_DINAMICO) = New HashSet(Of BLOQUEO_CUENTAS_DINAMICO)

End Class
