'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class BLOQUEO_CUENTAS_DINAMICO
    Public Property producto_contratado As Integer
    Public Property bloqueo_observacion As Byte
    Public Property fecha_bloqueo_proceso As Nullable(Of Date)
    Public Property consultor_bloquea As Short
    Public Property fecha_restriccion As Nullable(Of Date)
    Public Property tipo_bloqueo As Byte

    Public Overridable Property BLOQUEO_OBSERVACION1 As BLOQUEO_OBSERVACION
    Public Overridable Property PRODUCTO_CONTRATADO1 As PRODUCTO_CONTRATADO

End Class
