'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CANCELA_REACTIVA_CUENTAS
    Public Property consecutivo As Integer
    Public Property producto_contratado As Integer
    Public Property status_anterior As Short
    Public Property fecha As Date
    Public Property usuario As Short
    Public Property motivo As String

    Public Overridable Property PRODUCTO_CONTRATADO1 As PRODUCTO_CONTRATADO

End Class
