'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class CATALOGOSEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CATALOGOSEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property DIAS_FERIADOS() As DbSet(Of DIAS_FERIADOS)
    Public Overridable Property AGENCIA() As DbSet(Of AGENCIA)
    Public Overridable Property CLIENTE() As DbSet(Of CLIENTE)
    Public Overridable Property ORIGEN_CD() As DbSet(Of ORIGEN_CD)
    Public Overridable Property RENOVACION_CD() As DbSet(Of RENOVACION_CD)
    Public Overridable Property TIPO_CD() As DbSet(Of TIPO_CD)
    Public Overridable Property USUARIO() As DbSet(Of USUARIO)
    Public Overridable Property OPERA_SUCURSAL() As DbSet(Of OPERA_SUCURSAL)

End Class
