'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CERTIFICADO_DEPOSITO
    Public Property producto_contratado As Integer
    Public Property tipo_cd As Byte
    Public Property plazo As Short
    Public Property renovacion As Byte
    Public Property origen As Byte
    Public Property subtipo_cd As Nullable(Of Byte)
    Public Property operacion As Nullable(Of Integer)

    Public Overridable Property PRODUCTO_CONTRATADO1 As PRODUCTO_CONTRATADO
    Public Overridable Property OPERACION1 As OPERACION

End Class
