'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CLIENTE
    Public Property cuenta_cliente As String
    Public Property tratamiento As String
    Public Property nombre_cliente As String
    Public Property direccion_cliente As String
    Public Property cp_cliente As String
    Public Property telefono_cliente As String
    Public Property fax_cliente As String
    Public Property tipo_cliente As String
    Public Property fecha_alta As Date
    Public Property fecha_baja As Nullable(Of Date)
    Public Property ubicacion As Nullable(Of Short)
    Public Property funcionario As Integer
    Public Property tipo_retencion As Nullable(Of Byte)
    Public Property rfc As String
    Public Property apellido_paterno As String
    Public Property apellido_materno As String
    Public Property persona_moral As Byte
    Public Property UNIDAD_TEMP As String
    Public Property colonia_cliente As String
    Public Property cuenta_modificada As Nullable(Of Byte)
    Public Property cuenta_mancomunada As Nullable(Of Byte)
    Public Property cuenta_eje_pesos As String
    Public Property mnemonico As String
    Public Property deposito_inicial As Nullable(Of Byte)
    Public Property descripcion_deposito_inicial As String
    Public Property cuenta_mercury As String
    Public Property monto_deposito_inicial As Nullable(Of Decimal)
    Public Property documentacion As Nullable(Of Short)
    Public Property agencia As Nullable(Of Byte)
    Public Property tiene_chequera As Nullable(Of Byte)
    Public Property cuenta_houston As String
    Public Property fecha_banklink As Nullable(Of Date)
    Public Property fecha_cuenta_pesos As Nullable(Of Date)
    Public Property funcionario_pesos As Nullable(Of Integer)
    Public Property deposito_inicial_fed As Nullable(Of Decimal)
    Public Property deposito_inicial_suc As Nullable(Of Decimal)
    Public Property func_pesos As String
    Public Property calle As String
    Public Property no_ext As String
    Public Property no_int As String
    Public Property componente As String
    Public Property del_o_municipio As String
    Public Property shortname As String
    Public Property curp As String

End Class
