'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CODIGO_OPERACION_CED
    Public Property codigo_operacion As String
    Public Property codigo_leyenda As String
    Public Property nombre_servicio As String
    Public Property primer_renglon As String
    Public Property traduccion As String
    Public Property tipo_movimiento As Nullable(Of Byte)
    Public Property validaciones As String
    Public Property tipo_documento As Nullable(Of Byte)
    Public Property operacion_definida_global As Nullable(Of Short)

End Class
