'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CONCEPTO_DEFINIDO
    Public Property concepto_definido1 As Short
    Public Property descripcion_concepto_definido As String
    Public Property producto As Short
    Public Property valor_inicial As Decimal
    Public Property concepto_definido_global As Nullable(Of Short)
    Public Property agencia As Nullable(Of Byte)

    Public Overridable Property CONCEPTO As ICollection(Of CONCEPTO) = New HashSet(Of CONCEPTO)

End Class
