'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CONCEPTO
    Public Property producto_contratado As Integer
    Public Property concepto_definido As Short
    Public Property valor_concepto As Decimal

    Public Overridable Property PRODUCTO_CONTRATADO1 As PRODUCTO_CONTRATADO
    Public Overridable Property CONCEPTO_DEFINIDO1 As CONCEPTO_DEFINIDO

End Class
