'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CUENTA_EJE
    Public Property producto_contratado As Integer
    Public Property tipo_cuenta_eje As Byte
    Public Property tipo_cuenta_anterior As Nullable(Of Byte)

    Public Overridable Property PRODUCTO_CONTRATADO1 As PRODUCTO_CONTRATADO
    Public Overridable Property TIPO_CUENTA_EJE1 As TIPO_CUENTA_EJE

End Class
