'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DEPOSITO_CED
    Public Property operacion As Integer
    Public Property codigo_leyenda As String
    Public Property observaciones As String
    Public Property referencia As String
    Public Property tipo_cambio As Nullable(Of Decimal)
    Public Property codigo_operacion As String

    Public Overridable Property OPERACION1 As OPERACION

End Class
