'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DEPOSITO
    Public Property operacion As Integer
    Public Property en_firme As Byte
    Public Property destino As Byte
    Public Property otros As String
    Public Property tipo_documento As Nullable(Of Byte)
    Public Property otro_documento As String
    Public Property tipo_moneda As Nullable(Of Byte)
    Public Property folio_linea_servicio As Nullable(Of Integer)
    Public Property referencia_ced As Nullable(Of Integer)
    Public Property causa As String

    Public Overridable Property OPERACION1 As OPERACION
    Public Overridable Property TIPO_DOCUMENTO1 As TIPO_DOCUMENTO

End Class
