'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DEPOSITO_PME
    Public Property operacion As Integer
    Public Property centro_regional As String
    Public Property nombre_centro_regional As String
    Public Property plaza As String
    Public Property nombre_plaza As String
    Public Property sucursal As String
    Public Property nombre_sucursal As String
    Public Property referencia As Nullable(Of Integer)
    Public Property fecha_cierre As Nullable(Of Date)
    Public Property causa As String

    Public Overridable Property OPERACION1 As OPERACION

End Class
