'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class DETALLE_AUTORIZACION
    Public Property operacion As Integer
    Public Property numero_autorizacion As String
    Public Property codigo_transaccion As String
    Public Property operacion_bg As String
    Public Property fecha_alta As Date
    Public Property clave_gestor As String
    Public Property nombre_contacto As String
    Public Property paterno_contacto As String
    Public Property materno_contacto As String
    Public Property tipo_identificacion As String
    Public Property desc_identificacion As String
    Public Property estado_autorizacion As String
    Public Property causa As String

    Public Overridable Property ESTADO_AUTORIZACION1 As ESTADO_AUTORIZACION
    Public Overridable Property OPERACION1 As OPERACION

End Class
