'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ESTADO_AUTORIZACION
    Public Property estado_autorizacion1 As String
    Public Property desc_estado_autorizacion As String

    Public Overridable Property DETALLE_AUTORIZACION As ICollection(Of DETALLE_AUTORIZACION) = New HashSet(Of DETALLE_AUTORIZACION)

End Class
