'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EVENTO_PRODUCTO
    Public Property producto_contratado As Integer
    Public Property fecha_evento As Date
    Public Property status_producto As Short
    Public Property comentario_evento As String
    Public Property usuario As Short

    Public Overridable Property PRODUCTO_CONTRATADO1 As PRODUCTO_CONTRATADO

End Class
