'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class FUNCIONARIO
    Public Property funcionario1 As Integer
    Public Property unidad_organizacional As Nullable(Of Integer)
    Public Property nombre_funcionario As String
    Public Property apellido_paterno As String
    Public Property apellido_materno As String
    Public Property numero_funcionario As String
    Public Property telefono_funcionario As String
    Public Property fax_funcionario As String
    Public Property calle_funcionario As String
    Public Property colonia_funcionario As String
    Public Property ubicacion As Nullable(Of Short)
    Public Property cp_funcionario As String
    Public Property estrategico As Nullable(Of Short)
    Public Property activo As Nullable(Of Byte)
    Public Property numero_registro As String
    Public Property on_mni As Boolean
    Public Property on_bsi As Boolean
    Public Property on_harris As Boolean
    Public Property cr_opera As Nullable(Of Integer)
    Public Property bbvab As Boolean
    Public Property unidad_organizacional_anterior As String
    Public Property cr_opera_term As Nullable(Of Integer)
    Public Property fecha_alta As Nullable(Of Date)
    Public Property fecha_baja As Nullable(Of Date)
    Public Property fecha_ult_modif As Nullable(Of Date)

End Class
