'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HOLD
    Public Property producto_contratado As Integer
    Public Property fecha_equation As Date
    Public Property hold1 As Short
    Public Property descripcion1 As String
    Public Property descripcion2 As String
    Public Property descripcion3 As String
    Public Property descripcion4 As String
    Public Property usuario_equation As String
    Public Property secuencia_hold As Nullable(Of Integer)

    Public Overridable Property PRODUCTO_CONTRATADO1 As PRODUCTO_CONTRATADO

End Class
