'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class HOLD_RETIRO
    Public Property producto_contratado As Integer
    Public Property hold As Short
    Public Property operacion_retiro As Integer
    Public Property operacion_hold As Integer
    Public Property tipo As String

    Public Overridable Property PRODUCTO_CONTRATADO1 As PRODUCTO_CONTRATADO

End Class
