'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OPERACION_DEFINIDA
    Public Property operacion_definida1 As Short
    Public Property descripcion_operacion_definida As String
    Public Property producto As Short
    Public Property descripcion_kapiti As String
    Public Property code_kapiti_cliente As String
    Public Property code_kapiti_banco As String
    Public Property cuenta_kapiti_banco As String
    Public Property sufijo_kapiti_banco As String
    Public Property operacion_definida_global As Nullable(Of Short)
    Public Property agencia As Nullable(Of Byte)
    Public Property tipo_operacion As Nullable(Of Byte)
    Public Property descripcion_interfaz_ced As String

    Public Overridable Property OPERACION As ICollection(Of OPERACION) = New HashSet(Of OPERACION)

End Class
