'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OPERACION_SWIFT
    Public Property no_rep_swift As Integer
    Public Property operacion As Integer
    Public Property hora_envio As Nullable(Of Date)
    Public Property numero_reporte_202 As Nullable(Of Integer)

    Public Overridable Property OPERACION1 As OPERACION

End Class
