'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class OPERA_SUCURSAL
    Public Property opera_sucursal1 As Integer
    Public Property sucursal As String
    Public Property tipo_documento As Byte
    Public Property tit_referencia As String
    Public Property tit_referencia_ced As String
    Public Property cr_opera As Nullable(Of Integer)

End Class
