'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PRODUCTO
    Public Property producto1 As Short
    Public Property descripcion_producto As String
    Public Property sucursal_kapiti As Nullable(Of Short)
    Public Property sufijo_kapiti As Nullable(Of Short)
    Public Property producto_global As Nullable(Of Short)
    Public Property agencia As Nullable(Of Byte)

    Public Overridable Property PRODUCTO_CONTRATADO As ICollection(Of PRODUCTO_CONTRATADO) = New HashSet(Of PRODUCTO_CONTRATADO)

End Class
