'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PRODUCTO_CONTRATADO
    Public Property producto_contratado1 As Integer
    Public Property producto As Short
    Public Property cuenta_cliente As String
    Public Property clave_producto_contratado As String
    Public Property fecha_contratacion As Date
    Public Property fecha_vencimiento As Nullable(Of Date)
    Public Property status_producto As Nullable(Of Short)
    Public Property agencia As Nullable(Of Byte)

    Public Overridable Property PRODUCTO1 As PRODUCTO
    Public Overridable Property STATUS_PRODUCTO1 As STATUS_PRODUCTO
    Public Overridable Property OPERACION As ICollection(Of OPERACION) = New HashSet(Of OPERACION)
    Public Overridable Property CANCELA_REACTIVA_CUENTAS As ICollection(Of CANCELA_REACTIVA_CUENTAS) = New HashSet(Of CANCELA_REACTIVA_CUENTAS)
    Public Overridable Property APERTURA_SUCURSAL_MANUAL As APERTURA_SUCURSAL_MANUAL
    Public Overridable Property CONCEPTO As ICollection(Of CONCEPTO) = New HashSet(Of CONCEPTO)
    Public Overridable Property CUENTA_EJE As CUENTA_EJE
    Public Overridable Property BLOQUEO_CUENTAS_DINAMICO As ICollection(Of BLOQUEO_CUENTAS_DINAMICO) = New HashSet(Of BLOQUEO_CUENTAS_DINAMICO)
    Public Overridable Property DETALLE_STATUS As ICollection(Of DETALLE_STATUS) = New HashSet(Of DETALLE_STATUS)
    Public Overridable Property CERTIFICADO_DEPOSITO As CERTIFICADO_DEPOSITO
    Public Overridable Property HOLD As ICollection(Of HOLD) = New HashSet(Of HOLD)
    Public Overridable Property EVENTO_PRODUCTO As ICollection(Of EVENTO_PRODUCTO) = New HashSet(Of EVENTO_PRODUCTO)
    Public Overridable Property HOLD_RETIRO As HOLD_RETIRO

End Class
