'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RETIRO_ORDEN_PAGO
    Public Property operacion As Integer
    Public Property sujeto_a_recepcion As Boolean
    Public Property banco_en_EU As Boolean
    Public Property fondos_bancomer_mex As Boolean
    Public Property excento_comision As Boolean
    Public Property aba_intermediario As String
    Public Property cve_intermediario As String
    Public Property dato1_intermediario As String
    Public Property dato2_intermediario As String
    Public Property dato3_intermediario As String
    Public Property dato4_intermediario As String
    Public Property aba_corresponsal As String
    Public Property cve_corresponsal As String
    Public Property cta_corresponsal As String
    Public Property dato1_corresponsal As String
    Public Property dato2_corresponsal As String
    Public Property dato3_corresponsal As String
    Public Property dato4_corresponsal As String
    Public Property cta_beneficiario As String
    Public Property dato1_beneficiario As String
    Public Property dato2_beneficiario As String
    Public Property dato3_beneficiario As String
    Public Property dato4_beneficiario As String
    Public Property referencia1 As String
    Public Property referencia2 As String
    Public Property referencia3 As String
    Public Property referencia4 As String
    Public Property parcialmente_sujeto As Boolean
    Public Property contacto As String
    Public Property fed As Nullable(Of Integer)
    Public Property fecha_recepcion_fed As Nullable(Of Date)

    Public Overridable Property OPERACION1 As OPERACION

End Class
