'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class RETIRO_PME
    Public Property operacion As Integer
    Public Property causa As String
    Public Property centro_regional As String
    Public Property nombre_centro_regional As String
    Public Property plaza As String
    Public Property nombre_plaza As String
    Public Property sucursal As String
    Public Property nombre_sucursal As String
    Public Property cr_patrimonial As Nullable(Of Integer)
    Public Property referencia As Nullable(Of Integer)
    Public Property numero_cheque As Nullable(Of Decimal)
    Public Property tipo_documento As Nullable(Of Byte)
    Public Property tipo_moneda As Nullable(Of Byte)
    Public Property otro_documento As String
    Public Property referencia_ced As Nullable(Of Integer)

    Public Overridable Property OPERACION1 As OPERACION
    Public Overridable Property TIPO_DOCUMENTO1 As TIPO_DOCUMENTO

End Class
