'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class STATUS_PRODUCTO
    Public Property status_producto1 As Short
    Public Property descripcion_status As String
    Public Property producto As Nullable(Of Short)
    Public Property status_producto_global As Nullable(Of Short)
    Public Property agencia As Nullable(Of Byte)

    Public Overridable Property PRODUCTO_CONTRATADO As ICollection(Of PRODUCTO_CONTRATADO) = New HashSet(Of PRODUCTO_CONTRATADO)

End Class
