'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class TICKETEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=TICKETEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property PRODUCTO() As DbSet(Of PRODUCTO)
    Public Overridable Property PRODUCTO_CONTRATADO() As DbSet(Of PRODUCTO_CONTRATADO)
    Public Overridable Property STATUS_PRODUCTO() As DbSet(Of STATUS_PRODUCTO)
    Public Overridable Property OPERACION() As DbSet(Of OPERACION)
    Public Overridable Property OPERACION_DEFINIDA() As DbSet(Of OPERACION_DEFINIDA)
    Public Overridable Property CANCELA_REACTIVA_CUENTAS() As DbSet(Of CANCELA_REACTIVA_CUENTAS)
    Public Overridable Property APERTURA_SUCURSAL_MANUAL() As DbSet(Of APERTURA_SUCURSAL_MANUAL)
    Public Overridable Property BLOQUEO_OBSERVACION() As DbSet(Of BLOQUEO_OBSERVACION)
    Public Overridable Property CONCEPTO() As DbSet(Of CONCEPTO)
    Public Overridable Property CUENTA_EJE() As DbSet(Of CUENTA_EJE)
    Public Overridable Property TIPO_CUENTA_EJE() As DbSet(Of TIPO_CUENTA_EJE)
    Public Overridable Property BLOQUEO_CUENTAS_DINAMICO() As DbSet(Of BLOQUEO_CUENTAS_DINAMICO)
    Public Overridable Property DETALLE_STATUS() As DbSet(Of DETALLE_STATUS)
    Public Overridable Property CONCEPTO_DEFINIDO() As DbSet(Of CONCEPTO_DEFINIDO)
    Public Overridable Property RETIRO_ORDEN_PAGO() As DbSet(Of RETIRO_ORDEN_PAGO)
    Public Overridable Property COMPRA_CD() As DbSet(Of COMPRA_CD)
    Public Overridable Property COMPRA_TD_OVERNIGHT() As DbSet(Of COMPRA_TD_OVERNIGHT)
    Public Overridable Property CERTIFICADO_DEPOSITO() As DbSet(Of CERTIFICADO_DEPOSITO)
    Public Overridable Property HOLD() As DbSet(Of HOLD)
    Public Overridable Property EVENTO_PRODUCTO() As DbSet(Of EVENTO_PRODUCTO)
    Public Overridable Property HOLD_RETIRO() As DbSet(Of HOLD_RETIRO)
    Public Overridable Property BITACORA_ENVIO_SWIFT() As DbSet(Of BITACORA_ENVIO_SWIFT)
    Public Overridable Property OPERACION_SWIFT() As DbSet(Of OPERACION_SWIFT)
    Public Overridable Property DEPOSITO_PME() As DbSet(Of DEPOSITO_PME)
    Public Overridable Property DEPOSITO() As DbSet(Of DEPOSITO)
    Public Overridable Property DETALLE_AUTORIZACION() As DbSet(Of DETALLE_AUTORIZACION)
    Public Overridable Property ESTADO_AUTORIZACION() As DbSet(Of ESTADO_AUTORIZACION)
    Public Overridable Property TIPO_DOCUMENTO() As DbSet(Of TIPO_DOCUMENTO)
    Public Overridable Property TIPO_MONEDA() As DbSet(Of TIPO_MONEDA)
    Public Overridable Property DETALLE_INSTRUMENTO() As DbSet(Of DETALLE_INSTRUMENTO)
    Public Overridable Property RETIRO_PME() As DbSet(Of RETIRO_PME)
    Public Overridable Property TRASPASO() As DbSet(Of TRASPASO)
    Public Overridable Property TIPO_EVENTO_OPERACION() As DbSet(Of TIPO_EVENTO_OPERACION)
    Public Overridable Property DEPOSITO_CED() As DbSet(Of DEPOSITO_CED)
    Public Overridable Property OPERACION_PIU() As DbSet(Of OPERACION_PIU)
    Public Overridable Property CODIGO_OPERACION_CED() As DbSet(Of CODIGO_OPERACION_CED)
    Public Overridable Property OPERACION_PIU_BATCH() As DbSet(Of OPERACION_PIU_BATCH)
    Public Overridable Property RETIRO_CED() As DbSet(Of RETIRO_CED)

End Class
