'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TIPO_CUENTA_EJE
    Public Property tipo_cuenta_eje1 As Byte
    Public Property descripcion_tipo As String
    Public Property sufijo_kapiti As String

    Public Overridable Property CUENTA_EJE As ICollection(Of CUENTA_EJE) = New HashSet(Of CUENTA_EJE)

End Class
