'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TIPO_MONEDA
    Public Property tipo_moneda1 As Byte
    Public Property descripcion_moneda As String
    Public Property codigo_moneda As String

    Public Overridable Property DETALLE_INSTRUMENTO As ICollection(Of DETALLE_INSTRUMENTO) = New HashSet(Of DETALLE_INSTRUMENTO)

End Class
