'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TIPO_DOCUMENTO
    Public Property tipo_documento1 As Byte
    Public Property descripcion_documento As String
    Public Property operacion_definida_global As Short
    Public Property necesita_especificacion As Boolean
    Public Property status_folio As Boolean
    Public Property hora_inicio As Date
    Public Property hora_fin As Date
    Public Property tran_code As String
    Public Property otras_divisas As Boolean
    Public Property detalle_instrumento As Boolean
    Public Property orden As Nullable(Of Byte)
    Public Property titulo1 As String
    Public Property titulo2 As String
    Public Property activo As Boolean
    Public Property descripcion_detalle As String
    Public Property hora_ini_password As Nullable(Of Date)

    Public Overridable Property DEPOSITO As ICollection(Of DEPOSITO) = New HashSet(Of DEPOSITO)
    Public Overridable Property RETIRO_PME As ICollection(Of RETIRO_PME) = New HashSet(Of RETIRO_PME)

End Class
