'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TRASPASO
    Public Property operacion As Integer
    Public Property causa As String
    Public Property cuenta_destino As String
    Public Property operacion_deposito As Nullable(Of Integer)
    Public Property agencia_destino As Byte

    Public Overridable Property OPERACION1 As OPERACION

End Class
