'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class UNIDAD_ORGANIZACIONAL
    Public Property unidad_organizacional1 As Integer
    Public Property unidad_org_bancomer As String
    Public Property tipo_unidad_organizacional As Nullable(Of Byte)
    Public Property descripcion_unidad_organizacio As String
    Public Property unidad_organizacional_padre As Integer
    Public Property estrategica As Byte

End Class
