'------------------------------------------------------------------------------
' <auto-generated>
'     Este código se generó a partir de una plantilla.
'
'     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
'     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class USUARIO
    Public Property usuario1 As Short
    Public Property login As String
    Public Property password As String
    Public Property kapiti As String
    Public Property nombre_usuario As String
    Public Property origen_usuario As Nullable(Of Byte)
    Public Property fecha_cambio_password As Nullable(Of Date)
    Public Property fecha_ultimo_acceso As Nullable(Of Date)
    Public Property area_usuario As Nullable(Of Byte)
    Public Property login_erroneo As Nullable(Of Byte)
    Public Property colores1 As String
    Public Property colores2 As String
    Public Property colores3 As String
    Public Property adm_dd As String
    Public Property ultimo_pwd As String
    Public Property intentos_pregunas As Short
    Public Property id_corporativo As String

End Class
