//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CargaDiasFeriados
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIAS_FERIADOS
    {
        public System.DateTime fecha { get; set; }
        public Nullable<byte> tipo_dia_feriado { get; set; }
    }
}
